version: "3.9"

networks:
  my-network:

services:
  api:
    networks:
      - my-network
  db:
    networks:
      - my-network
  migrations:
    networks:
      - my-network
  frontend:
    networks:
      - my-network