name: GitHub Actions # дадим название нашему workflow

on: [ push ] # событие по которому запустится workflow
jobs:
  build_and_push: # первая часть - часть CI - собираем образ и пушим в docker hub
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2 # копирование кода на платформу GitHub
      - name: building
        run: docker build -t maksnd/todo_project:$GITHUB_RUN_ID . # сборка образа
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: docker push # отправляем сборку в docker hub
        run: docker push maksnd/todo_project:$GITHUB_RUN_ID